import {
  type FontCssProperties,
  getRequestHash,
  getRequestId,
  getScopedFontFamily,
} from '@/core/util'
import {
  type FontData,
  type NextFontGoogleOptions,
  optionsFromRequest,
} from './options'
import { type FontFallback, hasSizeAdjust } from '@/core/font-fallback'
import { HashableString, hashXxh3Hash64 } from '@/plugin/hash'
import {
  cleanUrl,
  createCachedImport,
  nextJsFilePath,
  splitExtension,
} from '@/plugin/util'
import { getFontAxes, getStylesheetUrl } from './util'
import type { NextFontRequest } from './request'
import type { PluginContext } from 'rolldown'
import { buildStylesheet } from './stylesheet'
import fs from 'node:fs/promises'
import { getFontFallback } from './font-fallback'
import path from 'node:path'

type Context = {
  build: boolean
  emitFile: PluginContext['emitFile']
  getFileName: PluginContext['getFileName']
}

export const GOOGLE_FONTS_STYLESHEET_URL = 'https://fonts.googleapis.com/css2'
// Always sending this user agent ensures consistent results from Google Fonts.
// Google Fonts will vary responses based on user agent, e.g. only returning
// references to certain font types for certain browsers.
export const USER_AGENT_FOR_GOOGLE_FONTS =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) ' +
  'AppleWebKit/537.36 (KHTML, like Gecko) ' +
  'Chrome/104.0.0.0 Safari/537.36'

// The google fonts plugin downloads fonts locally and transforms the url in the css into a
// specific format that is then intercepted later. This is the prefix we use for the new url.
export const GOOGLE_FONTS_INTERNAL_PREFIX =
  '@vercel/turbopack-next/internal/font/google/font'

export function nextFontGoogleReplacer() {
  return async function (source: string) {
    const filePath = cleanUrl(source)
    const query = filePath !== source ? source.slice(filePath.length + 1) : ''
    if (!query) return null

    const requestHash = getRequestHash(query)
    const searchParams = new URLSearchParams(
      `${query.startsWith('?') ? '' : '?'}${query}`
    )

    const fontData = await loadFontData()
    const options = fontOptionsFromQueryMap(query, fontData)

    const fallback = await getFontFallback(options)
    const properties = getFontCssProperties(options, fallback)

    return {
      path: `\0${nextJsFilePath('internal/font/google')}/${getRequestId(options.fontFamily, requestHash)}.js`,
      content: `import cssModule from "@vercel/turbopack-next/internal/font/google/cssmodule.module.css?${searchParams.toString()}";
const fontData = {
  className: cssModule.className,
  style: {
    fontFamily: "${properties.fontFamily}",
    ${properties.weight ? `fontWeight: ${properties.weight}, ` : ''}${properties.style ? `fontStyle: "${properties.style}",` : ''}
  },
};

if (cssModule.variable != null) {
  fontData.variable = cssModule.variable;
}

export default fontData;`,
    }
  }
}

// Intercepts requests for the css module made by the virtual JavaScript
// asset generated by the above replacer. Returns a VirtualSource of a CSS
// Module containing font face definitions and exporting class names for
// the font and an optional css variable.
export function nextFontGoogleCssModuleReplacer(
  fontFileMap: Map<string, Uint8Array>
) {
  return async function (this: Context, source: string) {
    const filePath = cleanUrl(source)
    const query = filePath !== source ? source.slice(filePath.length + 1) : ''
    if (!query) return null

    const requestHash = getRequestHash(query)
    const fontData = await loadFontData()
    const options = fontOptionsFromQueryMap(query, fontData)
    const stylesheetUrl = getStylesheetUrlFromOptions(options, fontData)
    const scopedFontFamily = getScopedFontFamily('webFont', options.fontFamily)
    const cssVirtualPath = `${nextJsFilePath('internal/font/google')}/${getRequestId(options.fontFamily, requestHash)}.module.css`

    // When running Next.js integration tests, use the mock data available in
    // process.env.NEXT_FONT_GOOGLE_MOCKED_RESPONSES instead of making real
    // requests to Google Fonts.
    const mockedResponsesPath = process.env.NEXT_FONT_GOOGLE_MOCKED_RESPONSES

    const stylesheetStr = await (mockedResponsesPath
      ? getMockStylesheet(stylesheetUrl, mockedResponsesPath)
      : fetchRealStylesheet(stylesheetUrl, cssVirtualPath))

    const tempFontFileMap = new Map<string, Uint8Array>()

    const fontFallback = await getFontFallback(options)
    const stylesheet =
      stylesheetStr != null
        ? await updateGoogleStylesheet.bind(this)(
            tempFontFileMap,
            stylesheetStr,
            options,
            scopedFontFamily,
            hasSizeAdjust(fontFallback)
          )
        : (() => {
            // If we're in production mode, we want to fail the build to ensure proper font
            // rendering.
            if (this.build) {
              throw new Error(
                `Failed to fetch \`${options.fontFamily}\`from Google Fonts.`
              )
            } else {
              console.error(
                `Failed to download \`${options.fontFamily}\` from Google Fonts. Using fallback`
              )
              return null
            }
          })()

    for (const [path, data] of tempFontFileMap) {
      fontFileMap.set(path, data)
    }

    return {
      path: cssVirtualPath,
      content: buildStylesheet(
        stylesheet ?? null,
        getFontCssProperties(options, fontFallback),
        fontFallback
      ),
      deps: Array.from(tempFontFileMap.keys()),
    }
  }
}

export type NextFontGoogleFontFileOptions = {
  url: string
  preload: boolean
  hasSizeAdjust: boolean
}

// Intercepts requests for the font made by the CSS
// asset generated by the above replacer.
// Mainly here to rename the asset for the manifest.
export async function nextFontGoogleFontFileReplacer(
  { url, preload, hasSizeAdjust: sizeAdjust }: NextFontGoogleFontFileOptions,
  fontFileMap: Map<string, Uint8Array>
) {
  const [filename, ext] = splitExtension(url)
  if (!ext) throw new Error(`Font url \`${url}\` is missing an extension`)

  let name = `${hashXxh3Hash64(new HashableString(filename)).toString(16).padStart(16, '0')}${sizeAdjust ? '-s' : ''}${preload ? '.p' : ''}`

  const fontVirtualPath = `${nextJsFilePath('internal/font/google')}/${name}.${ext}`

  return {
    path: fontVirtualPath,
    content: fontFileMap.has(fontVirtualPath)
      ? null
      : fetchFromGoogleFonts
          .bind({})(url, fontVirtualPath)
          .then((res) => res?.bytes()),
  }
}

const loadFontData = createCachedImport(async () =>
  import('@/google/font-data.json').then((mod) => mod.default)
)

async function updateGoogleStylesheet(
  this: Context,
  fontFileMap: Map<string, Uint8Array>,
  stylesheet: string,
  options: NextFontGoogleOptions,
  scopedFontFamily: string,
  hasSizeAdjust: boolean
): Promise<string> {
  let updatedStylesheet = stylesheet.replace(
    `font-family: '${options.fontFamily}';`,
    `font-family: '${scopedFontFamily}';`
  )

  const fontFiles = findFontFilesInCSS(
    updatedStylesheet,
    options.preload ? (options.subsets ?? []) : []
  )

  await Promise.all(
    fontFiles.map(async ({ fontUrl, preload }) => {
      const result = await nextFontGoogleFontFileReplacer(
        {
          url: fontUrl,
          preload,
          hasSizeAdjust,
        },
        fontFileMap
      )

      const content = await result.content
      const fileName =
        content != null && this.build
          ? this.getFileName(
              this.emitFile({
                type: 'asset',
                name: result.path,
                source: content,
              })
            )
          : result.path

      if (content != null) {
        fontFileMap.set(fileName, content)
      }

      updatedStylesheet = updatedStylesheet.replace(fontUrl, `/${fileName}`)
    })
  )

  return updatedStylesheet
}

type FontFile = {
  fontUrl: string
  preload: boolean
}

const findFontFilesInCSS = (
  css: string,
  subsetsToPreload: string[]
): FontFile[] => {
  const fontFiles: FontFile[] = []
  let currentSubset = ''

  const commentRE = /\/\* (.+?) \*\//
  const fontUrlRE = /src: url\((.+?)\)/

  for (const line of css.split('\n')) {
    const newSubset = line.match(commentRE)?.[1]
    if (newSubset) {
      currentSubset = newSubset
      continue
    }

    const fontUrl = line.match(fontUrlRE)?.[1]
    if (fontUrl == null) continue

    if (fontFiles.some((f) => f.fontUrl === fontUrl)) continue

    fontFiles.push({
      fontUrl,
      preload: subsetsToPreload.includes(currentSubset),
    })
  }

  return fontFiles
}

function getStylesheetUrlFromOptions(
  options: NextFontGoogleOptions,
  fontData: FontData
): string {
  const cssUrl =
    process.env.TURBOPACK_TEST_ONLY_MOCK_SERVER ?? GOOGLE_FONTS_STYLESHEET_URL

  return getStylesheetUrl(
    cssUrl,
    options.fontFamily,
    getFontAxes(
      fontData,
      options.fontFamily,
      options.weights,
      options.styles,
      options.selectedVariableAxes
    ),
    options.display
  )
}

function getFontCssProperties(
  options: NextFontGoogleOptions,
  fontFallback: FontFallback
): FontCssProperties {
  const scopedFontFamily = getScopedFontFamily('webFont', options.fontFamily)

  const fontFamilies = [`'${scopedFontFamily}'`]

  switch (fontFallback.type) {
    case 'manual':
      fontFamilies.push(...fontFallback.value)
      break
    case 'automatic':
      fontFamilies.push(`'${fontFallback.value.scopedFontFamily}'`)
      break
    case 'error':
      break
  }

  return {
    fontFamily: fontFamilies.join(', '),
    weight:
      options.weights.type === 'variable' || options.weights.values.length > 1
        ? undefined
        : options.weights.values[0] != null
          ? String(options.weights.values[0])
          : undefined,
    style: options.styles.length > 1 ? undefined : options.styles[0],
    variable: options.variable,
  }
}

function fontOptionsFromQueryMap(
  query: string,
  fontData: FontData
): NextFontGoogleOptions {
  const searchParams = new URLSearchParams(
    `${query.startsWith('?') ? '' : '?'}${query}`
  )

  if (searchParams.size !== 1) {
    throw new Error('"next-font/google queries must have exactly one entry"')
  }

  const entry = searchParams.entries().next().value![0] as string

  return optionsFromRequest(
    JSON.parse(entry) as NextFontRequest,
    new Map(Object.entries(fontData))
  )
}

async function fetchRealStylesheet(
  stylesheetUrl: string,
  cssVirtualPath: string
): Promise<string | null> {
  try {
    const body = await fetchFromGoogleFonts
      .bind({})(stylesheetUrl, cssVirtualPath)
      .then((res) => res?.text())
    return body ?? null
  } catch (err) {
    console.warn(`Failed to fetch stylesheet for ${cssVirtualPath}:`, err)
    return null
  }
}

async function fetchFromGoogleFonts(
  this: { warn?: (message: string) => void },
  url: string,
  virtualPath: string
): Promise<Response | null> {
  try {
    return fetch(url, {
      headers: {
        'User-Agent': USER_AGENT_FOR_GOOGLE_FONTS,
      },
      cache: 'force-cache',
    })
  } catch (err) {
    ;(this.warn ?? console.warn)(
      `Google Fonts fetch warning at ${virtualPath}: ${String(err)}`
    )
    return null
  }
}

async function getMockStylesheet(
  stylesheetUrl: string,
  mockedResponsesPath: string
): Promise<string | null> {
  const responsePath = path.resolve(mockedResponsesPath)

  let data: Record<string, string | null>
  try {
    const jsonContent = await fs.readFile(responsePath, 'utf-8')
    data = JSON.parse(jsonContent)
  } catch (err) {
    throw new Error(
      `Failed to read mocked responses at ${responsePath}: ${String(err)}`
    )
  }

  if (!(stylesheetUrl in data)) {
    throw new Error(`Mocked response for URL "${stylesheetUrl}" not found`)
  }

  return data[stylesheetUrl] ?? null
}
