name: CI

on:
  push:
    branches: ['main']
  pull_request:
    types: [opened, synchronize]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: taiki-e/checkout-action@3ab630d442e198ebb0ca30872832406ca01c46eb # v1.4.0

      - uses: oven-sh/setup-bun@v2

      - run: bun i --frozen-lockfile
      - run: bun run fmt --check
      - run: bun run lint --format github

  build:
    name: Build and Test
    timeout-minutes: 15
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}

    steps:
      - uses: taiki-e/checkout-action@3ab630d442e198ebb0ca30872832406ca01c46eb # v1.4.0

      - uses: oven-sh/setup-bun@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - run: bun i --frozen-lockfile
      - run: bun run build
      - run: bun run test
