name: CI

on:
  push:
    branches: ['main']
  pull_request:
    types: [opened, synchronize]

jobs:
  ci:
    runs-on: ubuntu-slim
    steps:
      - uses: taiki-e/checkout-action@83ed61bfbe2b8abbb3c66e8b65b1335484c70009 # v1.4.1
      - uses: voidzero-dev/setup-vp@v1
        with:
          node-version-file: '.node-version'
          cache: true
          run-install: false
      - run: vp i --frozen-lockfile
      - run: vp run build
      - run: vp check
      - run: vp test
