name: Release

on:
  workflow_dispatch:
    inputs:
      package:
        description: package to release
        required: true
        type: choice
        options:
          - "@next-font/vite"
          - next-font
      semver:
        description: 'Semver increment type'
        required: true
        default: 'patch'
        type: choice
        options:
          - major
          - minor
          - patch
          - alpha
          - beta
          - canary
      dry_run:
        description: 'Dry run (do not actually release)'
        required: false
        default: false
        type: boolean

permissions:
  id-token: write

jobs:
  stage:
    name: Stage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Configure Git
        run: |
          git config --global user.name vvv
          git config --global user.email 93486795+kijv@users.noreply.github.com

      - name: Prepare branch
        id: prepare-branch
        run: |
          git checkout -b release-${{ github.event.inputs.package }}
          echo "STAGE_BRANCH=$(git branch --show-current)" >> $GITHUB_OUTPUT

      - name: Release packages
        run: |
          PACKAGE="${{ github.event.inputs.package }}"
          if [ "${{ github.event.inputs.dry_run }}" = "true" ]; then
            bun xtask workspace $PACKAGE --bump --semver ${{ github.event.inputs.semver }} --dry-run
          else
            bun xtask workspace $PACKAGE --bump --semver ${{ github.event.inputs.semver }}
          fi

      - name: Stage
        if: github.event.inputs.dry_run != 'true'
        run: |
          git push origin ${{ steps.prepare-branch.outputs.STAGE_BRANCH }} --tags
  
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: stage
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun build

      - name: Test
        run: bun test
  
  publish:
    name: Publish to NPM
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: bun install

