name: Release

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-slim
    permissions:
      id-token: write
      contents: write
      pull-requests: write
    steps:
      - uses: taiki-e/checkout-action@83ed61bfbe2b8abbb3c66e8b65b1335484c70009 # v1.4.1
      - uses: voidzero-dev/setup-vp@v1
        with:
          node-version-file: '.node-version'
          cache: true
          run-install: false
      - run: vp i --frozen-lockfile
      - name: Changesets
        id: changesets
        uses: changesets/action@v1
        with:
          publish: vp run release
          version: vp run version
          title: release packages
          commit: release packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
